# Generated by Django 4.1.2 on 2022-12-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_director',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_excom',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_member',
        ),
    ]
