# Generated by Django 4.1.2 on 2022-12-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_is_customer_user_is_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_director',
            field=models.BooleanField(default=False, verbose_name='Is Director'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_excom',
            field=models.BooleanField(default=False, verbose_name='Is Excom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='Is Member'),
        ),
    ]
