# Generated by Django 4.1.2 on 2022-12-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_register_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_table',
            old_name='age',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='register_table',
            name='about',
        ),
        migrations.RemoveField(
            model_name='register_table',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='register_table',
            name='city',
        ),
        migrations.RemoveField(
            model_name='register_table',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='register_table',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='register_table',
            name='update_on',
        ),
        migrations.AddField(
            model_name='register_table',
            name='email',
            field=models.EmailField(blank=True, max_length=250),
        ),
    ]
