# Generated by Django 4.1.2 on 2022-12-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
