# Generated by Django 4.1.2 on 2022-12-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_register_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_table',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
