# Generated by Django 4.1.2 on 2023-01-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_on',
            new_name='updated_on',
        ),
    ]
