# Generated by Django 4.1.2 on 2023-01-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_created_on_user_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='register_table',
        ),
    ]
