# Generated by Django 4.1.2 on 2022-12-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=False)),
                ('time', models.TimeField(default=False)),
                ('location', models.TextField(max_length=200)),
                ('agenda', models.TextField(max_length=1000)),
                ('members', models.TextField(max_length=200)),
                ('decision', models.TextField(max_length=1000)),
            ],
        ),
    ]
