# Generated by Django 4.1.2 on 2023-01-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_minutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=False)),
                ('time', models.TimeField(default=False)),
                ('location', models.TextField(max_length=200)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['date']},
        ),
    ]
